spring:
  datasource:
    url: jdbc:mysql://registera.cbcsq8xej8ou.us-east-2.rds.amazonaws.com:3306/registera
    username: admin
    password: Saopaulo3
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO


