spring:
  datasource:
    url: ${datasourceUrl}
    username: ${datasourceUsername}
    password: ${datasourcePassword}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: ${hibernateDdlAuto}

logging:
  level:
    root: ${loggingLevelRoot}

