spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registrations
    username: root
    password: example
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
